### ISSUE TITLE
Understanding and Legality of data

### ISSUE THREAD

**Issue by dcooper160** [edwardchalstrey1/scoping-exercise#2]
- [x] Has this data been QC'd 
- [x] Is the data in a suitable format to analyse 
- [x] Can the data be legally used (licensing issues)
- [x] Is there more recent data since 2016
- [x] Is the data a wide enough scope, only refers to 33 out of 50 countries in Europe

**Comment by Benjamin-Kolicic** [comment]
Another Issue:
- [x] How can we be sure the data is unbiased

**Comment by Benjamin-Kolicic** [comment]
PI Response:
1. Yes it's from a reputable source
2. No, part of the job is to wrangle the data
3. It is under and free-use policy and is royalty-free (consent of use has been given)
4.  No as 2016 was the last census but secondary data can be used alongside an unbiased prediction to create "up to date" records
5. Yes a majority of Europe is fine, if the project goes well we will have the funding to expand to more European and Worldwide countries

**Comment by dcooper160** [comment]
> Another Issue:
> 
> * [x]  How can we be sure the data is unbiased

we could implement a Sampling scheme to make sure each country has a repressentitive number of records
